import { Appointment, AttendanceStatus } from '@/types/profile'

export const profileCalendarData: Appointment[] = [
  {
    appointmentName: '종강파티',
    groupName: '경영학과',
    scheduledAt: '2025-02-12T18:20:34',
    voteEndTime: '2026-02-10T18:20:59',
  },
  {
    appointmentName: '강릉여행',
    groupName: '찐친들',
    scheduledAt: '2025-02-22T18:20:34',
    voteEndTime: '2026-02-16T18:20:59',
  },
  {
    appointmentName: '기술 세미나',
    groupName: '개발자모임',
    scheduledAt: '2025-02-17T18:20:34',
    voteEndTime: '2026-02-12T18:20:59',
  },
  {
    appointmentName: '기술 세미나',
    groupName: '개발자모임',
    scheduledAt: '2025-02-17T18:20:34',
    voteEndTime: '2025-02-15T17:20:59',
  },
  {
    appointmentName: '월간 회의',
    groupName: '프로젝트 팀',
    scheduledAt: '2025-02-18T15:00:00',
    voteEndTime: '2025-02-14T14:00:00',
  },
]

export const AttendanceStatusData: AttendanceStatus[] = [
  {
    clubId: 1,
    clubName: '개발자 스터디 그룹 A',
    totalCount: 24,
    appointmentTotalCount: 20,
    lateTotalCount: 3,
    onTimeAttendanceTotalCount: 1,
  },
  {
    clubId: 2,
    clubName: '웰니스 클럽 B',
    totalCount: 18,
    appointmentTotalCount: 16,
    lateTotalCount: 1,
    onTimeAttendanceTotalCount: 1,
  },
  {
    clubId: 3,
    clubName: '영화 애호가 모임 C',
    totalCount: 30,
    appointmentTotalCount: 25,
    lateTotalCount: 4,
    onTimeAttendanceTotalCount: 1,
  },
  {
    clubId: 4,
    clubName: '독서 클럽 D',
    totalCount: 12,
    appointmentTotalCount: 10,
    lateTotalCount: 2,
    onTimeAttendanceTotalCount: 0,
  },
  {
    clubId: 5,
    clubName: '모험가 클럽 E',
    totalCount: 20,
    appointmentTotalCount: 17,
    lateTotalCount: 2,
    onTimeAttendanceTotalCount: 1,
  },
  {
    clubId: 6,
    clubName: '테크 토크 F',
    totalCount: 22,
    appointmentTotalCount: 19,
    lateTotalCount: 2,
    onTimeAttendanceTotalCount: 1,
  },
  {
    clubId: 7,
    clubName: '건강과 피트니스 G',
    totalCount: 15,
    appointmentTotalCount: 13,
    lateTotalCount: 1,
    onTimeAttendanceTotalCount: 1,
  },
  {
    clubId: 8,
    clubName: '음악 제작 H',
    totalCount: 26,
    appointmentTotalCount: 22,
    lateTotalCount: 3,
    onTimeAttendanceTotalCount: 1,
  },
  {
    clubId: 9,
    clubName: '크리에이티브 아트 I',
    totalCount: 18,
    appointmentTotalCount: 15,
    lateTotalCount: 2,
    onTimeAttendanceTotalCount: 1,
  },
  {
    clubId: 10,
    clubName: '사진 촬영 클럽 J',
    totalCount: 22,
    appointmentTotalCount: 18,
    lateTotalCount: 3,
    onTimeAttendanceTotalCount: 1,
  },
  {
    clubId: 11,
    clubName: '게임 개발 K',
    totalCount: 24,
    appointmentTotalCount: 20,
    lateTotalCount: 3,
    onTimeAttendanceTotalCount: 1,
  },
  {
    clubId: 12,
    clubName: '시네마 클럽 L',
    totalCount: 19,
    appointmentTotalCount: 15,
    lateTotalCount: 3,
    onTimeAttendanceTotalCount: 1,
  },
  {
    clubId: 13,
    clubName: '요리 클래스 M',
    totalCount: 21,
    appointmentTotalCount: 18,
    lateTotalCount: 2,
    onTimeAttendanceTotalCount: 1,
  },
  {
    clubId: 14,
    clubName: '공예 워크숍 N',
    totalCount: 23,
    appointmentTotalCount: 19,
    lateTotalCount: 3,
    onTimeAttendanceTotalCount: 1,
  },
  {
    clubId: 15,
    clubName: '자연 탐험 O',
    totalCount: 20,
    appointmentTotalCount: 16,
    lateTotalCount: 3,
    onTimeAttendanceTotalCount: 1,
  },
  {
    clubId: 16,
    clubName: '언어 교환 P',
    totalCount: 25,
    appointmentTotalCount: 21,
    lateTotalCount: 3,
    onTimeAttendanceTotalCount: 1,
  },
  {
    clubId: 17,
    clubName: '스포츠 팬 Q',
    totalCount: 22,
    appointmentTotalCount: 18,
    lateTotalCount: 3,
    onTimeAttendanceTotalCount: 1,
  },
  {
    clubId: 18,
    clubName: '패션 디자인 R',
    totalCount: 24,
    appointmentTotalCount: 20,
    lateTotalCount: 3,
    onTimeAttendanceTotalCount: 1,
  },
  {
    clubId: 19,
    clubName: '그래픽 디자인 S',
    totalCount: 21,
    appointmentTotalCount: 18,
    lateTotalCount: 2,
    onTimeAttendanceTotalCount: 1,
  },
  {
    clubId: 20,
    clubName: '건축학 스터디 T',
    totalCount: 25,
    appointmentTotalCount: 21,
    lateTotalCount: 3,
    onTimeAttendanceTotalCount: 1,
  },
]
