spring:
  config:
    import:
      - application-db.yml
      - application-auth.yml
      - application-aws.yml
springdoc:
  swagger-ui:
    path: /api-docs.html
  api-docs:
    path: /api-docs
  show-actuator: true
  default-produces-media-type: application/json